name: Java CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run Docker
      run: docker-compose -f src/docker/docker-compose.yml up -d
    - name: Wait for Docker
      run: |
          while ! nc -z localhost 5432 || ! nc -z localhost 6379 || ! nc -z localhost 9444; do
            echo "Waiting for Docker services..."
            sleep 5
          done
    - name: Verify with Maven
      run: mvn -B verify --file src/boot/pom.xml
    - name: Clean Docker
      run: docker-compose -f src/docker/docker-compose.yml down